### ISSUE TITLE
readme 수정 건의 

### ISSUE THREAD

**Issue by dongtimes2** [GDSC-Hongik/GDSC-1st-Frontend-Study#3]
git 명령어 설명 부분에 수정 건의사항이 있습니다. 

master -> main 으로 정정해야 할 것 같습니다.

**Comment by 9yujin** [comment]
감사합니다!! 추가로 조금더 수정해놓았습니다. 

현재 과제 커리큘럼이나 스터디 제출 방식 등은 첫번째 스터디 이전에 코어멤버 안에서 임시로 회의한 결과이구요, 첫번째 스터디 때 전체 멤버들과 더 구체적으로 이야기를 나눌 예정입니다!!
